added new tests
Hexlet/ru-test-assignments pull request #164
Opened 2022-12-21 11:20 UTC by MilaNick

Привет) Добавила пару тестов (Studika, Ютор)

2022-12-21 11:35 UTC, ashikov requested changes
Нужно поправить пару моментов

2022-12-21 11:35 UTC, ashikov commented on README.md
> +* [ООО ЮТОР]()
А зачем тут оформлено как ссылка, когда это не ссылка?

2022-12-21 11:35 UTC, ashikov commented on README.md
> +  *[Стажер фронтенд разработчик, 1 этап отбора](https://docs.google.com/document/d/1BK6lOSnTEtI0V5K5idK_QJU6CC5Iv1-lhpGAGDqftkA/edit?usp=sharing)
Не хватает пробела после астериска

2022-12-22 00:59 UTC, MilaNick commented on README.md
> +  *[Стажер фронтенд разработчик, 1 этап отбора](https://docs.google.com/document/d/1BK6lOSnTEtI0V5K5idK_QJU6CC5Iv1-lhpGAGDqftkA/edit?usp=sharing)
Ссылка убрана, пробел добавлен

2022-12-22 05:35 UTC, merged